env:
  - "RAILS_VERSION=3.0.20"
  - "RAILS_VERSION=3.1.12"
  - "RAILS_VERSION=3.2.22"
  - "RAILS_VERSION=4.0.13"
  - "RAILS_VERSION=4.1.15"
  - "RAILS_VERSION=4.2.6"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
before_install:
  - gem update --system
  - gem update bundler
