env:
  - "RAILS_VERSION=3.0.20"
  - "RAILS_VERSION=3.1.12"
  - "RAILS_VERSION=3.2.22.2"
  - "RAILS_VERSION=4.0.13"
  - "RAILS_VERSION=4.1.16"
  - "RAILS_VERSION=4.2.7"
  - "RAILS_VERSION=5.0.0"
rvm:
  - 2.2.5
  - 2.3.1
before_install:
  - gem update --system
  - gem update bundler
